# Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Set Globals & Functions

In [2]:
def checkData(x):
    print(f"\nInfo dos valores:\n")
    print(x.info())
    print(f"\nDescrição dos dados:\n\n{x.describe()}")
    return

def checkNaN(x):
    """This function receives a DataFrame and returns the count of NaN values for each column."""
    null_count = x.isna().sum()
    non_null_count = x.notnull().sum()
    print(f"Null values:\n {null_count}")
    print(f"Non-null values:\n {non_null_count}")
    return

def checkOutliers(x):
    """This functions receives a DataFrame and returns a DataFrame with the outliers.
    It takes as premise that the data is normally distributed."""
    dfOutliers  = pd.DataFrame()
    # Itera sobre as colunas númericas
    for column in x.select_dtypes(include=[np.number]).columns:
        # Calcula o 1 quartil (Q1)
        Q1 = x[column].quantile(0.25)
        # Calcula o 3 quartil (Q3)
        Q3 = x[column].quantile(0.75)
        # Calcula o Intervalo Interquartil (IQR)
        IQR = Q3 - Q1
        # Define os limites inferior e superior para outliers
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        # Identica os outliers da coluna atual e adiciona ao DataFrame de outliers
        outliers = x[(x[column] < lower_bound) | (x[column] > upper_bound)]
        # Concatene os outliers da coluna atual ao DataFrame de outliers
        dfOutliers = pd.concat([dfOutliers, outliers])
    outliersData = dfOutliers.drop_duplicates().reset_index(drop=True)
    return outliersData

def corr(x):
    plt.figure(figsize=(10,8))
    sns.heatmap(x.select_dtypes(include=[np.number]).corr(), annot=True)
    plt.show()
    return

def hist(x):
    """This function receives a DataFrame and returns a histogram of the data."""
    x.hist(bins=50, figsize=(25,10))
    plt.show()
    return

# Data Loading & Check

In [3]:
df_raw = pd.read_csv("train.csv")

In [4]:
checkData(df_raw)

Info dos valores:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4467 entries, 0 to 4466
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           4467 non-null   object
 1   Delivery_person_ID           4467 non-null   object
 2   Delivery_person_Age          4467 non-null   object
 3   Delivery_person_Ratings      4467 non-null   object
 4   Restaurant_latitude          4467 non-null   float64
 5   Restaurant_longitude         4467 non-null   float64
 6   Delivery_location_latitude   4467 non-null   float64
 7   Delivery_location_longitude  4467 non-null   float64
 8   Order_Date                   4467 non-null   object
 9   Time_Orderd                  4467 non-null   object
 10  Time_Order_picked            4467 non-null   object
 11  Weatherconditions            4467 non-null   object
 12  Road_traffic_density         4467 non-null   object
 13  Vehicle_condition            4467 non-null   int64
 14  Type_of_order                4467 non-null   object
 15  Type_of_vehicle              4467 non-null   object
 16  multiple_deliveries          4467 non-null   object
 17  Festival                     4467 non-null   object
 18  City                         4466 non-null   object
 19  Time_taken(min)              4466 non-null   object
dtypes: float64(4), int64(1), object(15)
memory usage: 698.1+ KB
None

Descrição dos dados:

       Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
count          4467.000000           4467.000000                 4467.000000
mean             16.873720             69.855186                   17.345751
std               8.320083             23.490634                    7.436276
min             -30.902872            -88.322337                    0.010000
25%              12.906229             73.170000                   12.969496
50%              18.546258             75.894377                   18.619299
75%              22.725835             78.013330                   22.781857
max              30.914057             88.433452                   31.035562

       Delivery_location_longitude  Vehicle_condition
count                  4467.000000        4467.000000
mean                     70.509414           1.022386
std                      21.655254           0.840340
min                       0.010000           0.000000
25%                      73.280937           0.000000
50%                      75.996362           1.000000
75%                      78.081576           2.000000
max                      88.563452           3.000000

In [5]:
df_raw.sample(30)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
4080,0x7e2f,RANCHIRES17DEL01,31,5,23.374878,85.335739,23.384878,85.345739,09-03-2022,10:45:00,10:55:00,conditions Sunny,Low,1,Drinks,scooter,1,No,Urban,(min) 13
1816,0xa034,SURRES13DEL03,28,4.8,21.170096,72.789122,21.200096,72.819122,28-03-2022,22:45:00,22:55:00,conditions Sandstorms,Low,2,Snack,electric_scooter,1,No,Metropolitian,(min) 17
1922,0xc92f,BHPRES18DEL01,26,4.6,23.234631,77.401663,23.304631,77.471663,18-02-2022,21:55:00,22:00:00,conditions Sandstorms,Jam,2,Meal,electric_scooter,0,No,Urban,(min) 15
2349,0x922,SURRES13DEL02,NaN,NaN,21.170096,72.789122,21.300096,72.919122,23-03-2022,NaN,20:40:00,conditions NaN,NaN,0,Buffet,motorcycle,0,No,Metropolitian,(min) 39
2767,0xb890,VADRES02DEL01,25,5,0.000000,0.000000,0.110000,0.110000,16-03-2022,19:00:00,19:05:00,conditions Fog,Medium,0,Drinks,motorcycle,0,No,Metropolitian,(min) 30
476,0xcc11,AURGRES05DEL02,38,5,19.875522,75.367127,19.925522,75.417127,15-02-2022,21:20:00,21:35:00,conditions Sandstorms,Jam,1,Meal,scooter,1,No,Metropolitian,(min) 34
1496,0xa17a,HYDRES11DEL03,20,4.3,17.430448,78.418213,17.520448,78.508213,14-03-2022,21:30:00,21:45:00,conditions Cloudy,Jam,1,Drinks,scooter,1,No,Metropolitian,(min) 35
624,0x8d48,JAPRES18DEL03,36,4.8,26.913987,75.752891,26.943987,75.782891,13-03-2022,23:10:00,23:20:00,conditions Cloudy,Low,0,Meal,motorcycle,1,No,Urban,(min) 20
2825,0xc59a,LUDHRES12DEL03,26,4.6,30.893244,75.821817,30.983244,75.911817,14-02-2022,17:35:00,17:45:00,conditions Sunny,Medium,0,Meal,motorcycle,1,No,Metropolitian,(min) 29
1249,0x158c,HYDRES09DEL01,34,4.7,17.431668,78.408321,17.441668,78.418321,26-03-2022,11:55:00,12:10:00,conditions Stormy,High,0,Meal,motorcycle,3,No,Metropolitian,(min) 44
2296,0x2282,INDORES08DEL03,33,4.9,22.725748,75.898497,22.815748,75.988497,04-04-2022,19:15:00,19:30:00,conditions Fog,Jam,2,Buffet,scooter,1,No,Metropolitian,(min) 40
1002,0x88c1,SURRES04DEL03,28,4.8,21.173493,72.801953,21.263493,72.891953,27-03-2022,19:50:00,20:05:00,conditions Stormy,Jam,1,Buffet,scooter,0,No,Metropolitian,(min) 19
1834,0x98f9,PUNERES09DEL02,21,5,18.536562,73.896485,18.666562,74.026485,06-04-2022,18:10:00,18:20:00,conditions Sandstorms,Medium,2,Buffet,scooter,1,No,Metropolitian,(min) 23
862,0x6742,MUMRES13DEL03,24,4.5,19.178321,72.834715,19.238321,72.894715,15-03-2022,23:40:00,23:45:00,conditions Fog,Low,0,Meal,motorcycle,0,No,Metropolitian,(min) 24
4047,0x811c,MUMRES17DEL01,21,4.7,19.121999,72.908493,19.231999,73.018493,08-03-2022,22:55:00,23:00:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Metropolitian,(min) 15
3627,0x642,INDORES09DEL03,NaN,NaN,22.725835,75.887648,22.785835,75.947648,13-03-2022,NaN,21:25:00,conditions Stormy,Jam,2,Meal,scooter,0,No,Urban,(min) 34
1416,0xe161,KNPRES11DEL03,27,4.8,26.474986,80.342796,26.564986,80.432796,16-02-2022,22:00:00,22:05:00,conditions Sunny,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 28
189,0x7405,SURRES19DEL01,36,4.9,21.149669,72.772629,21.219669,72.842629,02-03-2022,23:00:00,23:15:00,conditions Windy,Low,2,Buffet,motorcycle,0,No,Metropolitian,(min) 21
205,0x6055,JAPRES18DEL02,31,4,26.913987,75.752891,26.993987,75.832891,18-03-2022,17:50:00,18:05:00,conditions Fog,Medium,1,Snack,motorcycle,2,No,Metropolitian,(min) 39
4009,0xdd93,LUDHRES16DEL02,27,4.8,30.895817,75.813112,30.975817,75.893112,12-02-2022,18:50:00,19:05:00,conditions Cloudy,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 44
3821,0x82cf,PUNERES09DEL02,24,5,18.536562,73.896485,18.556562,73.916485,30-03-2022,08:55:00,09:05:00,conditions Sunny,Low,2,Drinks,scooter,1,No,Metropolitian,(min) 22
4192,0x9562,PUNERES18DEL02,34,4.7,18.593481,73.785901,18.723481,73.915901,04-04-2022,23:10:00,23:15:00,conditions Cloudy,Low,0,Buffet,motorcycle,1,No,Metropolitian,(min) 37
3172,0x4672,VADRES15DEL03,20,4.8,0.000000,0.000000,0.060000,0.060000,15-03-2022,17:25:00,17:35:00,conditions Sandstorms,Medium,0,Meal,motorcycle,1,No,Metropolitian,(min) 16
3148,0x2e64,BANGRES04DEL02,34,3.9,12.980410,77.640489,13.060410,77.720489,02-03-2022,22:10:00,22:20:00,conditions Cloudy,Low,2,Drinks,electric_scooter,1,No,Metropolitian,(min) 33
1706,0xa858,JAPRES12DEL01,30,4.7,26.902908,75.792934,26.942908,75.832934,01-03-2022,16:50:00,17:05:00,conditions Fog,Medium,2,Snack,motorcycle,1,No,Metropolitian,(min) 15
118,0x3ec5,RANCHIRES01DEL03,20,4.9,23.416792,85.316842,23.506792,85.406842,20-03-2022,22:10:00,22:20:00,conditions Sandstorms,Low,0,Meal,motorcycle,1,No,Metropolitian,(min) 17
2590,0x3608,INDORES17DEL01,39,4.8,22.761226,75.887522,22.871226,75.997522,12-03-2022,17:30:00,17:35:00,conditions Sunny,Medium,1,Buffet,motorcycle,0,No,Metropolitian,(min) 21
1585,0x7fc8,RANCHIRES03DEL01,25,4.6,0.000000,0.000000,0.110000,0.110000,16-03-2022,18:00:00,18:15:00,conditions Stormy,Medium,2,Drinks,motorcycle,1,No,Metropolitian,(min) 19
3817,0x138c,VADRES20DEL02,NaN,NaN,22.311358,73.164798,22.441358,73.294798,31-03-2022,NaN,19:55:00,conditions Stormy,Jam,2,Buffet,motorcycle,0,No,Urban,(min) 24
425,0xc003,DEHRES13DEL02,NaN,NaN,-30.366322,-78.070453,30.496322,78.200453,18-02-2022,NaN,22:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,(min) 20

# Clear & Transform

Clearly some columns have NaN values, but they are not appearing on the NaNs check. It can be because they are object types or are stored as string and have some weird formatting like " NaN", with a blank space.<br>First step is to remove all spaces from string columns, then convert them to the appropiate type and fill with the most appropriate value.

In [ ]:
df_clear = df_raw
# Remove blank spaces from strings.
df_clear = df_clear.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
# Convert to numeric types where needed.
df_clear["Delivery_person_Age"] = df_clear["Delivery_person_Age"].apply(pd.to_numeric, errors="coerce").astype("Int64")
df_clear["Delivery_person_Ratings"] = df_clear["Delivery_person_Ratings"].apply(pd.to_numeric, errors="coerce")
df_clear["multiple_deliveries"] = df_clear["multiple_deliveries"].apply(pd.to_numeric, errors="coerce").astype("Int64")
# Convert dates and times from object to date.time
df_clear["Order_Date"] = pd.to_datetime(df_clear["Order_Date"], format="%d-%m-%Y")

In [17]:
checkNaN(df_clear)

Null values:
 ID                               0
Delivery_person_ID               0
Delivery_person_Age            189
Delivery_person_Ratings        195
Restaurant_latitude              0
Restaurant_longitude             0
Delivery_location_latitude       0
Delivery_location_longitude      0
Order_Date                       0
Time_Orderd                      0
Time_Order_picked                0
Weatherconditions                0
Road_traffic_density             0
Vehicle_condition                0
Type_of_order                    0
Type_of_vehicle                  0
multiple_deliveries            104
Festival                         0
City                             1
Time_taken(min)                  1
dtype: int64
Non-null values:
 ID                             4467
Delivery_person_ID             4467
Delivery_person_Age            4278
Delivery_person_Ratings        4272
Restaurant_latitude            4467
Restaurant_longitude           4467
Delivery_location_latitude     4467
Delivery_location_longitude    4467
Order_Date                     4467
Time_Orderd                    4467
Time_Order_picked              4467
Weatherconditions              4467
Road_traffic_density           4467
Vehicle_condition              4467
Type_of_order                  4467
Type_of_vehicle                4467
multiple_deliveries            4363
Festival                       4467
City                           4466
Time_taken(min)                4466
dtype: int64

In [18]:
df_clear.dtypes

ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                     Int64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                     Int64
Festival                               object
City                                   object
Time_taken(min)                        object
dtype: object